In [3]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [4]:
df=pd.read_csv('ShopSmart_Customers.csv')
df.head()

,CustomerID,Age,Gender,Income,ProductsViewed,CartItems,TimeOnSite,PreviousPurchases,DiscountUsed,Membership,FavoriteCategory,Purchased,AmountSpent
0,1,20,Male,24114,39,7,19,11,30,Silver,Books,1,7514
1,2,57,Female,84965,40,5,37,25,3,Silver,Books,1,10648
2,3,51,Male,56321,17,9,39,3,22,Platinum,Books,1,9002
3,4,57,Male,93297,37,2,21,25,1,Silver,Fashion,1,8881
4,5,44,Male,116652,39,2,8,7,21,Silver,Home,1,7116

In [5]:
print('Shape:',df.shape)
print('\nColumns:')
print(df.columns)
print('\nData Types')
print(df.dtypes)

Shape: (500, 13)

Columns:
Index(['CustomerID', 'Age', 'Gender', 'Income', 'ProductsViewed', 'CartItems',
       'TimeOnSite', 'PreviousPurchases', 'DiscountUsed', 'Membership',
       'FavoriteCategory', 'Purchased', 'AmountSpent'],
      dtype='object')

Data Types
CustomerID            int64
Age                   int64
Gender               object
Income                int64
ProductsViewed        int64
CartItems             int64
TimeOnSite            int64
PreviousPurchases     int64
DiscountUsed          int64
Membership           object
FavoriteCategory     object
Purchased             int64
AmountSpent           int64
dtype: object

In [6]:
df.describe()

,CustomerID,Age,Income,ProductsViewed,CartItems,TimeOnSite,PreviousPurchases,DiscountUsed,Purchased,AmountSpent
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.00000,500.000000
mean,250.500000,41.428000,87556.388000,25.460000,4.356000,29.830000,14.852000,19.06800,0.95800,8558.034000
std,144.481833,13.569565,37710.299661,13.825291,2.824397,16.651115,8.638712,11.55571,0.20079,3224.867606
min,1.000000,18.000000,20207.000000,1.000000,0.000000,1.000000,0.000000,0.00000,0.00000,0.000000
25%,125.750000,29.750000,54571.250000,14.000000,2.000000,16.000000,7.000000,9.00000,1.00000,6730.750000
50%,250.500000,42.000000,88597.500000,24.500000,4.000000,30.000000,15.000000,19.00000,1.00000,8779.500000
75%,375.250000,53.000000,120186.750000,37.000000,7.000000,44.000000,22.250000,28.25000,1.00000,10704.500000
max,500.000000,64.000000,149992.000000,49.000000,9.000000,59.000000,29.000000,39.00000,1.00000,16326.000000

In [9]:
print('Customers:',len(df))
print('Purchased:', df['Purchased'].sum())
print('Average Spending:',round(df['AmountSpent'].mean(),2))
print('\nHighest Spender')
print(df.loc[df['AmountSpent'].idxmax()])

Customers: 500
Purchased: 479
Average Spending: 8558.03

Highest Spender
CustomerID              281
Age                      62
Gender               Female
Income               145654
ProductsViewed            4
CartItems                 9
TimeOnSite                9
PreviousPurchases        28
DiscountUsed              9
Membership             Gold
FavoriteCategory      Books
Purchased                 1
AmountSpent           16326
Name: 280, dtype: object

In [10]:
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Membership']=le.fit_transform(df['Membership'])
df['FavoriteCategory']=le.fit_transform(df['FavoriteCategory'])

In [15]:
X=df.drop(['CustomerID','Purchased','AmountSpent'], axis=1)
y=df['Purchased']
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)
pred=dt.predict(X_test)
print('Decision Tree Accuracy:',accuracy_score(y_test,pred))
print('\nConfusion Matrix')
print(confusion_matrix(y_test,pred))

Decision Tree Accuracy: 0.96

Confusion Matrix
[[ 3  2]
 [ 2 93]]

In [17]:
new_customer=[[30,1,60000,20,3,15,5,10,1,2]]
print('Purchase Pridiction:', dt.predict(new_customer)[0])

Purchase Pridiction: 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [20]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
knn_pred=knn.predict(X_test)
print('KNN Accuracy:',accuracy_score(y_test,knn_pred))

KNN Accuracy: 0.95

In [25]:
X_reg=df.drop(['CustomerID','Purchased','AmountSpent'],axis=1)
y_reg=df['AmountSpent']
X_train_reg,X_test_reg,y_train_reg,y_test_reg=train_test_split(
    X_reg,y_reg,test_size=0.2,random_state=42
)
lr=LinearRegression()
lr.fit(X_train_reg,y_train_reg)
amount=lr.predict([[30,1,60000,20,3,15,5,10,1,2]])
print('Predicted Spending:',amount[0])

Predicted Spending: 4477.686668606446

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(